"""add course_code to materials

Revision ID: 0b8a6d20484d
Revises: 9492aff33d01
Create Date: 2026-04-19 17:35:00.180416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8a6d20484d'
down_revision = '9492aff33d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=30), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('course_code')

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
