"""add question type hint explanation

Revision ID: 3234ff827d54
Revises: 0b8a6d20484d
Create Date: 2026-04-21 18:53:27.850594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3234ff827d54'
down_revision = '0b8a6d20484d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('explanation')
        batch_op.drop_column('hint')
        batch_op.drop_column('question_type')

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
