"""add admin role to users

Revision ID: 9b12330aed7d
Revises: 6990f6d02e3d
Create Date: 2026-04-28 19:02:35.624540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b12330aed7d'
down_revision = '6990f6d02e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('material_notes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])

    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz_attempts', ['attempt_id'], ['id'])
        batch_op.create_foreign_key(None, 'choices', ['selected_choice_id'], ['id'])
        batch_op.create_foreign_key(None, 'choices', ['correct_choice_id'], ['id'])
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('material_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
